### ISSUE TITLE
Protocol: File transfer outside of JSON-RPC

### ISSUE THREAD

**Issue by gordonwritescode** [Storj/node-storj#16]
Perhaps we can still transmit file chunk in the JSON RPC message by encoding it with base91 instead of hex. 

Seems promising and reduce the complexity of opening a separate connection and using a different protocol to transfer chunks. 

http://base91.sourceforge.net/

**Comment by gordonwritescode** [comment]
@robertspm

**Comment by gordonwritescode** [comment]
https://github.com/mscdex/base91.js

**Comment by robertsdotpm** [comment]
It's still no where near as efficient as pure binary data but I'd consider it a good compromise for short - medium term. 

My concern with this current design is that most servers aren't exactly optimised to accept huge amounts of data in the POST request - the file field is normally used and then the data can be easily buffered to /tmp. But with something like POST, its potentially all just in memory and that could add up to bad concurrency / scaling if the shards are like 128 mbs each (or if you're doing multiple transfers at once.) So we probably still do need to use something different eventually.

**Comment by gordonwritescode** [comment]
Yes, this doesn't work well for large chunks. Let's think about other options. Maybe a separate data channel is needed.

Or maybe websockets works for this since we are already over HTTP.

**Comment by gordonwritescode** [comment]
The CONSIGN RPC could just exchange a token for upgrading the HTTP connection to WS and pump the raw binary data over.

**Comment by gordonwritescode** [comment]
http://binaryjs.com/
